trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageRepository: myjob1
  containerRegistry: myjobregistry.azurecr.io
  dockerfilePath: MyJob1/MyJob1/Dockerfile
  resourceGroup: SingleServe
  containerAppJob: myjob1
  containerAppEnv: my-my-job-env
  tag: $(Build.BuildId)

steps:

- script: ls -R $(Build.SourcesDirectory)
  displayName: "Show repo structure"

- task: AzureCLI@2
  displayName: Login to Azure
  inputs:
    azureSubscription: 'MyAzureServiceConnection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Logged in"

- task: Docker@2
  displayName: Build and Push image to ACR
  inputs:
    command: buildAndPush
    containerRegistry: 'MyAcrServiceConnection'
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    tags: |
      $(tag)
      latest


- task: AzureCLI@2
  displayName: Update Container Apps Job
  inputs:
    azureSubscription: 'MyAzureServiceConnection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az containerapp job update --name $(containerAppJob) --resource-group $(resourceGroup) --image $(containerRegistry)/$(imageRepository):$(tag)